project_name: md2xk6
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    goos: ["linux", "windows", "darwin"]
    goarch: ["amd64", "arm64"]
    flags: ["-trimpath"]
    env: ["CGO_ENABLED=0"]
    ldflags:
      - "-s -w"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next+{{.ShortCommit}}{{if .IsGitDirty}}.dirty{{else}}{{end}}"
