# File generated by cdo from README.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  all      Clean build'
	@echo '  build    Build executable'
	@echo '  clean    Clean the working directory'
	@echo '  format   Format the go source codes'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate the Makefile'
	@echo '  security Run security and vulnerability checks'
	@echo '  test     Run the tests'

# Clean build
.PHONY: all
all: clean format security lint test build makefile

# Build executable
.PHONY: build
build: 
	@(\
		goreleaser build --clean --snapshot --single-target;\
	)

# Clean the working directory
.PHONY: clean
clean: 
	@(\
		rm -rf ./md2xk6 ./md2xk6.exe ./k6 ./k6.exe ./build ./dist;\
	)

# Format the go source codes
.PHONY: format
format: 
	@(\
		go fmt ./...;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		golangci-lint run ./...;\
	)

# Generate the Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Run security and vulnerability checks
.PHONY: security
security: 
	@(\
		gosec -quiet ./...;\
		govulncheck ./...;\
	)

# Run the tests
.PHONY: test
test: 
	@(\
		go test -count 1 -race -timeout 2m ./...;\
	)

