name: Validate

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: [".github/**"]

  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  validate:
    name: Validate
    uses: grafana/xk6/.github/workflows/tooling-validate.yml@v1.1.5
    permissions:
      contents: read
    with:
      go-version: "1.24.x"
      go-versions: '["1.24.x"]'
      golangci-lint-version: "v2.1.2"
      goreleaser-version: "2.8.2"
      platforms: '["ubuntu-latest"]'
      k6-versions: '["v1.3.0"]'
